/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Work = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'locationDescription' : IDL.Text,
  'jobTitle' : IDL.Text,
  'category' : IDL.Text,
  'workId' : IDL.Text,
});
export const Worker = IDL.Record({
  'bankAccountNumber' : IDL.Text,
  'husbandFatherName' : IDL.Text,
  'enrollmentPhotoId' : IDL.Text,
  'caste' : IDL.Text,
  'name' : IDL.Text,
  'bankIfsc' : IDL.Text,
  'bankName' : IDL.Text,
  'jobTitle' : IDL.Text,
  'employeeId' : IDL.Text,
  'village' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'phone' : IDL.Text,
  'bankBranchName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AttendanceRecord = IDL.Record({
  'workerId' : IDL.Text,
  'checkInPhotoId' : IDL.Text,
  'checkInTime' : Time,
  'recordId' : IDL.Text,
  'checkOutTime' : IDL.Opt(Time),
  'workId' : IDL.Text,
  'checkInLat' : IDL.Float64,
  'checkInLng' : IDL.Float64,
  'checkOutLat' : IDL.Opt(IDL.Float64),
  'checkOutLng' : IDL.Opt(IDL.Float64),
  'checkOutPhotoId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addWork' : IDL.Func([Work], [], []),
  'addWorker' : IDL.Func([Worker], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'getAllWorks' : IDL.Func([], [IDL.Vec(Work)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByWork' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByWorker' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMasterEntryGrantees' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getRegisteredUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getTodayCheckIns' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWork' : IDL.Func([IDL.Text], [Work], ['query']),
  'getWorker' : IDL.Func([IDL.Text], [Worker], ['query']),
  'grantMasterEntryPermission' : IDL.Func([IDL.Principal], [], []),
  'hasMasterEntryPermission' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordCheckIn' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, Time, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'recordCheckOut' : IDL.Func(
      [IDL.Text, IDL.Text, Time, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'removeWork' : IDL.Func([IDL.Text], [], []),
  'removeWorker' : IDL.Func([IDL.Text], [], []),
  'revokeMasterEntryPermission' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateWork' : IDL.Func([IDL.Text, Work], [], []),
  'updateWorker' : IDL.Func([IDL.Text, Worker], [], []),
  'uploadPhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Work = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'locationDescription' : IDL.Text,
    'jobTitle' : IDL.Text,
    'category' : IDL.Text,
    'workId' : IDL.Text,
  });
  const Worker = IDL.Record({
    'bankAccountNumber' : IDL.Text,
    'husbandFatherName' : IDL.Text,
    'enrollmentPhotoId' : IDL.Text,
    'caste' : IDL.Text,
    'name' : IDL.Text,
    'bankIfsc' : IDL.Text,
    'bankName' : IDL.Text,
    'jobTitle' : IDL.Text,
    'employeeId' : IDL.Text,
    'village' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'phone' : IDL.Text,
    'bankBranchName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AttendanceRecord = IDL.Record({
    'workerId' : IDL.Text,
    'checkInPhotoId' : IDL.Text,
    'checkInTime' : Time,
    'recordId' : IDL.Text,
    'checkOutTime' : IDL.Opt(Time),
    'workId' : IDL.Text,
    'checkInLat' : IDL.Float64,
    'checkInLng' : IDL.Float64,
    'checkOutLat' : IDL.Opt(IDL.Float64),
    'checkOutLng' : IDL.Opt(IDL.Float64),
    'checkOutPhotoId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addWork' : IDL.Func([Work], [], []),
    'addWorker' : IDL.Func([Worker], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'getAllWorks' : IDL.Func([], [IDL.Vec(Work)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByWork' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByWorker' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMasterEntryGrantees' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getRegisteredUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getTodayCheckIns' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWork' : IDL.Func([IDL.Text], [Work], ['query']),
    'getWorker' : IDL.Func([IDL.Text], [Worker], ['query']),
    'grantMasterEntryPermission' : IDL.Func([IDL.Principal], [], []),
    'hasMasterEntryPermission' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordCheckIn' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'recordCheckOut' : IDL.Func(
        [IDL.Text, IDL.Text, Time, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'removeWork' : IDL.Func([IDL.Text], [], []),
    'removeWorker' : IDL.Func([IDL.Text], [], []),
    'revokeMasterEntryPermission' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateWork' : IDL.Func([IDL.Text, Work], [], []),
    'updateWorker' : IDL.Func([IDL.Text, Worker], [], []),
    'uploadPhoto' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };