/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface AttendanceRecord {
  'workerId' : string,
  'checkInPhotoId' : string,
  'checkInTime' : Time,
  'recordId' : string,
  'checkOutTime' : [] | [Time],
  'workId' : string,
  'checkInLat' : number,
  'checkInLng' : number,
  'checkOutLat' : [] | [number],
  'checkOutLng' : [] | [number],
  'checkOutPhotoId' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'employeeId' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Work {
  'date' : string,
  'name' : string,
  'locationDescription' : string,
  'jobTitle' : string,
  'category' : string,
  'workId' : string,
}
export interface Worker {
  'bankAccountNumber' : string,
  'husbandFatherName' : string,
  'enrollmentPhotoId' : string,
  'caste' : string,
  'name' : string,
  'bankIfsc' : string,
  'bankName' : string,
  'jobTitle' : string,
  'employeeId' : string,
  'village' : string,
  'aadhaarNumber' : string,
  'phone' : string,
  'bankBranchName' : string,
}
export interface WorkerInput {
  'bankAccountNumber' : string,
  'husbandFatherName' : string,
  'enrollmentPhotoId' : string,
  'caste' : string,
  'name' : string,
  'bankIfsc' : string,
  'bankName' : string,
  'jobTitle' : string,
  'village' : string,
  'aadhaarNumber' : string,
  'phone' : string,
  'bankBranchName' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addWork' : ActorMethod<[Work], undefined>,
  'addWorker' : ActorMethod<[WorkerInput], string>,
  'assignAdminId' : ActorMethod<[Principal], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllWorkers' : ActorMethod<[], Array<Worker>>,
  'getAllWorks' : ActorMethod<[], Array<Work>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByWork' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByWorker' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMasterEntryGrantees' : ActorMethod<[], Array<Principal>>,
  'getMyId' : ActorMethod<[], string>,
  'getRegisteredUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getTodayCheckIns' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWork' : ActorMethod<[string], Work>,
  'getWorker' : ActorMethod<[string], Worker>,
  'grantMasterEntryPermission' : ActorMethod<[Principal], undefined>,
  'hasMasterEntryPermission' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'recordCheckIn' : ActorMethod<
    [string, string, string, string, Time, number, number],
    undefined
  >,
  'recordCheckOut' : ActorMethod<
    [string, string, Time, number, number],
    undefined
  >,
  'removeWork' : ActorMethod<[string], undefined>,
  'removeWorker' : ActorMethod<[string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'revokeMasterEntryPermission' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateWork' : ActorMethod<[string, Work], undefined>,
  'updateWorker' : ActorMethod<[string, Worker], undefined>,
  'uploadPhoto' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];